In [5]:
#import all necessary libraries
import pandas as pd
import numpy as np
import nltk
import re
from nltk.stem import WordNetLemmatizer 
from sklearn.metrics import accuracy_score

In [20]:
# read excel file
d = pd.read_csv('IMDB.csv')
d.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [21]:
# doing data cleaning with module re
def preprocess_row(row):
    row = str(row).lower()
    row = re.sub(r"\<[^<>]*\>", "", row)
    row = re.sub(r'[^A-Za-z ]+', '', row)
    
    return row

In [22]:
# then changing positive to 1 and negative to 0
d['review'] = d['review'].map(lambda x: preprocess_row(x))
d['sentiment'] = d['sentiment'].map(lambda x: 1 if x=='positive' else 0)

In [23]:
d.head()

review  sentiment
0  one of the other reviewers has mentioned that ...          1
1  a wonderful little production the filming tech...          1
2  i thought this was a wonderful way to spend ti...          1
3  basically theres a family where a little boy j...          0
4  petter matteis love in the time of money is a ...          1

In [24]:
d.shape

(50000, 2)

In [25]:
#divide into two parts x and y
x = d.iloc[:, :-1].values
y = d.iloc[:, -1].values

In [26]:
print(x)

[['one of the other reviewers has mentioned that after watching just  oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictu

In [27]:
print(y)

[1 1 1 ... 0 0 0]


In [28]:
# using split we divide by x_train and y_train
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2,random_state= 123)

In [29]:
print(x_train)

[['ok first off there may be a spoiler here since i dont know what constitutes giving out too much information my subject line says it all but surely people will want to know why its so stupidfirst off this film follows a bunch of yuppies as they go to a sports game in chicago but wind up taking the wrong exit and winding up in the ghetto scary huh well first of all emilio is driving everyone in the worlds most overblown rvwinnebago tricked out with satellite dishes and crap like that on it so these guys are going to a sports game i forget which though likely the bulls or the white sox since theyre near the ohsoscary ghetto yet they cant even make it down the freeway without having an onboard viewing command center that would put espn to shame yet theyre smart enough to earn livings that would pay for the stuff but are such sports fans that they dont even know which exit to get off at on their way to the game they so lovei gave up on the movie within a half hour after that but the reas

In [30]:
print(x_test)

[['this movie was beyond awful it was a pimple on the as of the movie industry i know that every movie cant be a hit or for that matter even average but the responsible parties that got together for this epic dud should have been able to see that they had a ticking time bomb on their hands i cant help but think that the cast would get together in between scenes and console each other for being in such a massive heap of dung i can hear it now you getting paid nope you i understand that this flick was more than likely made on a shoe string budget but even with that taken into account it still couldve been better you wait for the appearance of a monstercreature and when you finally see it its a big yawnim so mad at myself for spending a  on this stinker']
 ['as of this writing john carpenters halloween is nearing its th anniversary it has since spawned  sequels a remake a whole mess of imitations and every year around halloween when they do those top  scariest movies lists its always on t

In [31]:
print(y_train)

[0 0 0 ... 1 1 0]


In [32]:
print(y_test)

[0 1 1 ... 1 0 1]


# TfidVectorizer

create matrix from features

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
vectorizer = TfidfVectorizer()

the function .squeeze() help changing dataframe to series

In [35]:
X = vectorizer.fit_transform(x_train.squeeze())

In [36]:
X.shape

(40000, 186693)

# Build Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
logModel = LogisticRegression(max_iter=1000)

In [39]:
logModel.fit(X, y_train.squeeze())

LogisticRegression(max_iter=1000)

In [40]:
accuracy_score(logModel.predict(X), y_train.squeeze())

0.931375

# Import Grid Search

In [41]:
from sklearn.model_selection import GridSearchCV

In [42]:
grid = {"penalty":["l1","l2"], "C":np.logspace(-4,4, 20)}

In [46]:
logreg_cv = GridSearchCV(logModel,grid)
logreg_cv.fit(X, y_train.squeeze())

C:\Users\Alser\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
100 fits failed out of a total of 200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Alser\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Alser\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Alser\AppData\Local\Programs\Pyth

GridSearchCV(estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                         'penalty': ['l1', 'l2']})

In [49]:
print("tuned hyperparameters :(best parameters) ",logreg_cv.best_params_)
print("accuracy :", logreg_cv.best_score_)

tuned hyperparameters :(best parameters)  {'C': 11.288378916846883, 'penalty': 'l2'}
accuracy : 0.896725


In [50]:
logreg2 = LogisticRegression(C=1438.4498828766,penalty="l2")
logreg2.fit(X, y_train.squeeze())
print("Score", logreg2.score(X, y_train.squeeze()))

Score 1.0


C:\Users\Alser\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [51]:
vectorizer_test = vectorizer.transform(x_test.squeeze())

In [52]:
y_pred = logModel.predict(vectorizer_test)

In [53]:
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [54]:
y_test.squeeze()

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [55]:
accuracy_score(y_pred, y_test.squeeze())

0.8937